- README.md
> Update README.md to add tutorials links

- Plugins/SofaUnityAPI/GraphicAPI/SofaGraphicAPI.cs
- Plugins/SofaUnityAPI/GraphicAPI/SofaGraphicOGL_Test.cs
- Scenes/SofaScenes/VirtualXRayScene.scn
- Scripts/Core/System/PluginManager.cs
See merge request [infinytech3d/SofaUnity!4](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/4)
> It will need VirtualXray update + SAPAPI update beforehand:
https://gitlab.com/infinytech3d/VirtualXRay/-/merge_requests/1
[sofaadvancephysicsapi!4 (merged)](https://gitlab.com/infinytech3d/sofaadvancephysicsapi/-/merge_requests/4)
> [Plugin][XRay] Add VirtualXray plugin integration into Unity/SAPAPI

- .gitignore
- Scenes/SofaScenes/liver.py
- Scenes/SofaScenes/liver.py.meta
- Scripts/Editor/Config/CopyConfigPostProcessor.cs
- Scripts/Editor/SofaContextEditor.cs
See merge request [infinytech3d/SofaUnity!6](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/6)
Work done to integrate python scenes: 
- Add mechanism to handle python scene.
- Add interface in Editor
- Add liver python example
> [Feature] Add mechanism to handle python scenes 

- Plugins/SU_Imaging/Scripts/InitImagingPlugin.cs
- Plugins/SU_Imaging/Scripts/InitImagingPlugin.cs.meta
- Scripts/Core/System/PluginManager.cs
- Scripts/Editor/SofaContextEditor.cs
- Scripts/SofaContext.cs
See merge request [infinytech3d/SofaUnity!12](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/12)
Make PluginManager a singleton and add method to automatically register plugin if class is present in the project.
> [Full API] Update PluginManager to have an automatic behavior. 

- Plugins/SofaUnityAPI/BaseAPI/SofaBaseMeshAPI.cs
- Scripts/Core/Components/SofaMesh.cs
- Scripts/Core/Topology/SofaMeshTopology.cs
- Scripts/Editor/Components/SofaMeshEditor.cs
See merge request [infinytech3d/SofaUnity!25](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/25)
- also add drawing of forces
> [Full API] Add bindings and support to retrieve MechanicalObject Forces

- Plugins/SofaUnityAPI/BaseAPI/SofaBaseComponentAPI.cs
- Plugins/SofaUnityAPI/GraphicAPI/AbstractSofaGraphicCall.cs
- Plugins/SofaUnityAPI/SofaContextAPI.cs
- Scripts/Core/Data/SofaData.cs
- Scripts/Core/Data/SofaDataArchiver.cs
- Scripts/Editor/Components/SofaBaseComponentEditor.cs
- Scripts/Editor/Config/CopyConfigPostProcessor.cs
- Scripts/SofaContext.cs
See merge request [infinytech3d/SofaUnity!27](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/27)
**Add:**
- Support of Vec2i and vec3i Data
**Fix:**
- Crash of SofaGraphicCAll api if not in openGL mode.
> [Full API] Add support of Vec2i and vec3i Data for Release v20.12.00

- Plugins/SofaUnityAPI/ComponentsAPI/SofaDAGNodeAPI.cs
- Plugins/Virtual Capsule Endoscopy/Scripts/SofaCapsuleController.cs
- Scripts/Core/Components/SofaMesh.cs
- Scripts/Core/Components/SofaVisualModel.cs
- Scripts/Core/DAGNode/SofaDAGNodeManager.cs
- Scripts/Core/Data/SofaData.cs
- Scripts/Core/Data/SofaDataArchiver.cs
- Scripts/Core/System/PluginManager.cs
- Scripts/Editor/Components/SofaBaseComponentEditor.cs
- Scripts/Modules/Components/SofaBeamModel.cs
Also remove some unwanted logs
> [Full API] Fix Data parsing for basic types

- Plugins/SofaUnityAPI/SofaContextAPI.cs
- Scripts/Core/Base/SofaBaseComponent.cs
- Scripts/Core/Components/SofaComponentFactory.cs
- Scripts/Core/DAGNode/SofaDAGNode.cs
- Scripts/Core/System/PluginManager.cs
- Scripts/Modules/Controllers/ObjectController.cs
- Scripts/SofaContext.cs
- Scripts/Utils/ThirdPersonCamera.cs
See merge request [infinytech3d/SofaUnity!29](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/29)
**Fix:**
- Fix problem of VisualComponent creation failed at parsing
- Fix remove creation of empty gameObject when SOFA component is not supported
- Fix restore old behavior of thirdPerson camera controller by setting the heart beating movement as an option
- Update Graph parsing to handle Sofa Ode solver and Sofa Linear solver
- Update plugin Manager to handle new plugin from SOFA master
> [Full API] Bug fixes on SofaContext creation and SOFA scene parsing 

- Plugins/SofaUnityAPI/BaseAPI/SofaBaseMeshAPI.cs
- Scripts/Core/Components/SofaMesh.cs
- Scripts/Core/Topology/SofaMeshTopology.cs
- Scripts/Core/Topology/TopologyElements.cs
Improve all the TopologyElement class to really store the topology structure of an element as arrays of indices and add the hexahedral mesh handling in the SofaMeshTopology class
See merge request [infinytech3d/SofaUnity!30](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/30)
> [Full API] Add support for Hexahedral mesh 

- Plugins/SofaUnityAPI/BaseAPI/SofaBaseComponentAPI.cs
- Scripts/Core/Base/SofaBaseComponent.cs
- Scripts/Core/Base/SofaBaseData.cs
- Scripts/Core/Data/SofaData.cs
- Scripts/Core/Data/SofaDataArchiver.cs
- Scripts/Editor/Components/SofaBaseComponentEditor.cs
- Scripts/Utils/Texture2DFromRaw.cs
See merge request [infinytech3d/SofaUnity!31](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/31)
**Add:**
- Add option to get Data counter, flags (like readonly, to show, etc.) and check if dirty method
- Remove old_SofaData compatibility class
- Update DataArchiver to use a single list of BaseData and cast to the corresponding specification depending on the type of Data.
- Fix serialisation and add backward compatibility for this new dataArray
> [Full API] Improve SOFA Data communication between SOFA and Unity

- Scripts/Core/Components/SofaComponentFactory.cs
- Scripts/Core/Components/SofaVisualModel.cs
See merge request [infinytech3d/SofaUnity!33](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/33)
> [Fix] VisualModel topology change handling when SOFA mesh increase 

- Plugins/SofaUnityAPI/SofaContextAPI.cs
- Scripts/Core/Base/SofaBaseComponent.cs
- Scripts/Core/Components/SofaFEMForceField.cs
- Scripts/Core/DAGNode/SofaDAGNode.cs
- Scripts/Core/DAGNode/SofaDAGNodeManager.cs
- Scripts/Core/System/PluginManager.cs
See merge request [infinytech3d/SofaUnity!34](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/34)
**Fix:**
- Problem of multiple root node when deleting reloading SOFA scene
- Set default FEM material if HDRP or normal pipeline
- **Hack: Unactive svaing of Data for the moment**
> [Full API] Various fixes on root Node and scene creation

- Scenes/Benchmarks/Python3_Liver.unity
- Scenes/Benchmarks/Python3_Liver.unity.meta
- Scenes/SofaScenes/liver.py
- Scripts/Core/System/PluginManager.cs
- Scripts/Core/System/SceneFileManager.cs
- Scripts/Editor/SofaContextEditor.cs
See merge request [infinytech3d/SofaUnity!43](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/43)
Force SofaPython3.dll loading when loading python file
Need fixed version of PythonEnvironment using ini file.
> [Full API][src] Fix python loading scene

- Doc/Readme.txt
- Plugins/SofaUnityAPI/BaseAPI/SofaBaseMeshAPI.cs
- Scripts/Core/Components/SofaMesh.cs
- Scripts/Core/Topology/SofaMeshTopology.cs
> [Full API][src] Add method to setPosition in mehcanicalObject using float[]

- Plugins/SofaUnityAPI/SofaContextAPI.cs
- Scripts/Core/System/PluginManager.cs
- Scripts/Core/System/SceneFileManager.cs
- Scripts/SofaContext.cs
- Scripts/Utils/GenerateZIP.cs
- Scripts/Utils/KeyActionsRecorder.cs
- Scripts/Utils/Utility_SharpZipCommands.cs
See merge request [infinytech3d/SofaUnity!53](https://gitlab.com/infinytech3d/SofaUnity/-/merge_requests/53)
This will need SharpZipLib and I dont know if it is possible to integrate into the Assets, as it is a package (or whatever name it is)
- disable plugin for android
- fix the keyboard controller timing
- implement a system to archive the assets and then unzip at 1st launch for android
> [Full API][src] Update SofaUnity scripts to support android build 

- Core/Resources/Materials/UnlitRed.mat
- Core/Resources/Materials/UnlitRed.mat.meta
- Core/Scripts/Modules/Collision.meta
- Core/Scripts/Modules/Collision/SofaCollisionDisplay.cs
- Core/Scripts/Modules/Collision/SofaCollisionDisplay.cs.meta
This is a screenshot of the result:
> [src] Add SofaCollisionDisplay component and a unlit material to be used

- Core/Scripts/Core/System/PluginManager.cs
- Scenes/Demos/Python.meta
- Scenes/Demos/Python/LiverPyhon.unity
- Scenes/Demos/Python/LiverPyhon.unity.meta
- Scenes/Demos/Python/LiverPyhonController.unity
- Scenes/Demos/Python/LiverPyhonController.unity.meta
- Scenes/SofaScenes/liver_interaction.py
- Scenes/SofaScenes/liver_interaction.py.meta
- Scenes/SofaScenes/raptor-tetra2triangle-CUDA.scn
- Scenes/SofaScenes/raptor-tetra2triangle.scn
- Add a new scene using a pythonScriptController in background!
- Add SOFA menu in raptor benchmarks
> [scenes] Restore example using python SOFA scene and CUDA benchmarkes

- Core/Scripts/Core/Components/SofaVisualModel.cs
- Minor update to `SofaVisualModel`: added **getter and setter** for a protected variable, making it useful for **sphere mapping** on Sofa Objects.
> Minor update, added get/set on a protected variable

- Scenes/SofaScenes/CollisionSimple.scn
- Scenes/SofaScenes/CubeAdvCarvingWithRefinement.scn
- Scenes/SofaScenes/CubeCarving.scn
- Scenes/SofaScenes/CubeInteraction.scn
- Scenes/SofaScenes/Cube_CarvingTexcoords.scn
- Scenes/SofaScenes/Cylinder-tetra2triangle.scn
- Scenes/SofaScenes/HeatBeam.scn
- Scenes/SofaScenes/SPHDemo.scn
- Scenes/SofaScenes/SquareTissue_01_gravity.scn
- Scenes/SofaScenes/SquareTissue_02_interaction.scn
- Scenes/SofaScenes/SurfacePressureForceField.scn
- Scenes/SofaScenes/TriangleSurfaceCutting.scn
- Scenes/SofaScenes/beamDemo.scn
- Scenes/SofaScenes/caduceus.scn
- Scenes/SofaScenes/liver-HD-CUDA.scn
- Scenes/SofaScenes/liver-HD-FastCoritational.scn
- Scenes/SofaScenes/liver-HD.scn
- Scenes/SofaScenes/liver-tetra2triangle-CUDA.scn
- Scenes/SofaScenes/liver-tetra2triangle.scn
- Scenes/SofaScenes/liver-tetra2triangleVR.scn
- Scenes/SofaScenes/liver.scn
- Scenes/SofaScenes/liver2-cut-CUDA.scn
- Scenes/SofaScenes/liver2-cut.scn
- Scenes/SofaScenes/liver2.scn
- Scenes/SofaScenes/raptor-tetra2triangle-CUDA.scn
- Scenes/SofaScenes/raptor-tetra2triangle.scn
- Scenes/SofaScenes/tissue.scn
> [scenes] Fix errors in SOFA scene due to change in recent version of SOFA

- Core/Scripts/Core/Components/SofaMesh.cs
- Core/Scripts/Modules/Controllers/SofaRigidMapper.cs
- Core/Scripts/Modules/Controllers/SofaRigidMapper.cs.meta
> [src] Add SofaRigidMapper to match a unity Transform to a Rigid coord from SOFA
